export const teamLogos = [
  "AC Milan.png",
  "AS Monaco.png",
  "Roma.png",
  "Arsenal.png",
  "Aston Villa.png",
  "Atalanta.png",
  "Athletic Bilbao.png",
  "Atletico Madrid.png",
  "FC Barcelona.png",
  "Bayer Leverkusen.png",
  "Bayern Munich.png",
  "Bologna.png",
  "Borussia Dortmund.png",
  "Brighton.png",
  "Chelsea.png",
  "Eintracht Frankfurt.png",
  "Fiorentina.png",
  "Girona.png",
  "Inter Milan.png",
  "Juventus.png",
  "Lazio.png",
  "Lille.png",
  "Liverpool.png",
  "Lyon.png",
  "Manchester City.png",
  "Manchester United.png",
  "Montpellier HSC.png",
  "Newcastle United.png",
  "OGC Nice.png",
  "Marseille.png",
  "Paris SG.png",
  "RB Leipzig.png",
  "RC Lens.png",
  "Real Betis.png",
  "Robbers FC.png",
  "Real Sociedad.png",
  "Freiburg.png",
  "Napoli.png",
  "Sevilla.png",
  "Brest.png",
  "Rennes.png",
  "Torino.png",
  "Tottenham Hotspur.png",
  "Valencia.png",
  "VfB Stuttgart.png",
  "Villarreal.png",
  "SV Werder Bremen.png",
  "West Ham United.png"
];
